name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Android SDK installieren
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      # ZIP aus dem Repo entpacken (Dateiname muss passen!)
      - name: Unpack project
        run: |
          unzip -q NegativeScannerApp_Buildable.zip -d src
          ls -la src

      # Gradle (System-Gradle) installieren – da kein Wrapper im Projekt liegt
      - name: Install Gradle 8.6
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.6
          echo "GRADLE_HOME=$(sdk home gradle 8.6)" >> $GITHUB_ENV
          echo "$GRADLE_HOME/bin" >> $GITHUB_PATH

      - name: Build debug APK
        working-directory: src
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: src/app/build/outputs/apk/debug/app-debug.apk
